branches:
  only:
    - master
    - /^sentinel.+$/
    - /^test_development-.*$/
    - smurawski/publish_to_acceptance
env:
  global:
    - PATH=$HOME/.cargo/bin:$PATH
matrix:
  include:
    - os: linux
      env:
        - STEAM_ROLLER=true
        - AFFECTED_DIRS="Cargo\.toml|Cargo\.lock|components/hab|components/common|components/core|components/builder-depot-client|components/http-client|components/sup|components/butterfly"
        # HAB_ORIGIN_KEY
        - secure: "uZ70GE8qK3GBgs7ZIsoy5DhPlHNs2hoLxLBGKq+u+0XrE017pOnW6mNHsn7J7i2r8CPtd4KFsFEN52wZSA+Sf96MFIL2w9E+geykBgbRMZzv4icuCf0xSGwm4iRMgZ9A08TfurMX6y6N+4JNsrCv9syVNuGq09EL2wLHPXOQhesMpodijQLcFikxfEXXbaWla1xHnYxJk+fbvYDoXVCbdqnpdeLTmGuQHFaaNI7jm1B3L/dl+IGZxwFdvqBT3G9mHiXBdyi8bALs7rcZNdV7PqtFFpp98zIeqwNHtHPd5cBRmqDRTRxucRSACS/lurrz9J+001a9RjPvUkYlLrn0hQY9pN6oo+kCpN/1r0bc17i4FbGx7R73FnFgPK/cno0ENBFygNZn7/jg6cENgjkBlHsZhc1+L1xhILo46nQU9XbWJrwelVYUOOGXI76tECOkGhkglx1vYK8fcMVLJMhL7psgPpbGbDJQDuAKhHS+75txNK+356ompNL+YUzeWZc4KSGZCNTQsPK+rsGttmA+JXtAaquFaY5xwSgyKHwETiSVg4dYXb3xh6goNxf2JTOZOosWaypyykHqcqsqCu2fzIDdmkgCx6I5/5q8I/7Z0es0jlUpHamlihZwe4E5YdYFCSouaDoeTnVdJKVI1p9fnAjpFqjivFgqLE/Z504vCNU="
        - BINTRAY_USER=smurawski
        # BINTRAY_KEY
        - secure: "CHOiAfgFYbUBwYNIx7yJ7Y6697IzoX5zZtxHnByblU7Mei990vP+wUMjWrp2OY4I5UKdfSg5bkUtkEHBMUdoaiZZB+420dnZWPX94hQEYAGSdFzsgZlNZlu9vwnHout6+tDhylW0eIv7yMB1BViyOpeGxJ5rgCCmdDBEF5uWfnzuOMSeaOmcMQe24mzHY7vxIwfqJwEbVD08AOtJXVp2Kk0nLoA0GfJS1ZCcibK6TbXuZfUwYmF9jaZZdQj26UH8KtkiKYLy4Ti1c54XLwVahGeszBdi3xCAY6OWidAaTtnvEahtltXRl0HQCmhgLxpuZ/94lB4Mo4TqSf9NgZS7pqDB35YpYddy2hwW5HZFZlZoXgAqCTT+70NB0hoICpvNlvo4p7zRB7PVHbipgg64eA/OlLW+Bd4KXTHn+y+JrN1g9pDR9YF2lVewbmtzKbmxgQZYIrSK9SVZNP30DeN6uoedAxFFZGqgmPoC6Fcu5HG9Y1BY08HRVwRxLtLj8bciKgMHLNSKfVOdNlFac9nGn65aqenRGEmCd4wyjMZ7gd74V75aMdZozhFacDva0Qw5hRzhnJ8rYXBzG0juyodznMtVCARlRijPn0TW9LjYNb8+5f7LoxtywRmCNwYBB1OWghOePhWGMHBVAYTLzalIkX4WR0fc+xdhOq6lfAbgU4s="
        # BINTRAY_PASSPHRASE
        - secure: "XkZuLadu8aGACYdDN9QLUvuuGciiC8PahELGn2gfI8ILeIozzsWCclmNp2eKfduYsAu0otdps2dHAI1VwYH6+xGq+6byMMpXaXbQl3fahMe2vwaREpstmjbglWMNHcBqH4Bccx3aMxZjROO6NeT1U49uk7lKW+Enf+Dhw90L8sVP3v/xbmynYnue32heeQklkNH57RZ3uWJOUOPxOn5vcXsI0PqvJ8i53qIiUDQLivjLmOJUuudQiU/WP6rpewiIMoPO/REfyxq3gkCcYkzeXxytpVLEFwWjS6mvpLQbTJ+8/tp06sLXBxqknFboEWsqcraswROXi4ZXpubraFFNO/9jn9c1RaSmJqBEIQEK0/4K5VDYjukWMWpMQcwGq/I5dqUaDZJpoWPGqvw9b3zgsZNjlvLq2FEeuQEj2eD2Z4S5/PpgQRFhJMS+uMdPpingQMQAn9y83bZeDdtakWcX/IRjMBSF+UXCaXfTF9SWwURsCqakMEQhtZ+A3g5MAtZ6N/2QMsUcI7K56PjxXJiRSnZw821+VJgkpbk8Z8M2koZ6+Jy4jOGrUvDVGZ8umj3ipNmX8nFjP2s8jS7ihfIuG33p1fNw2397dEf0pDnPdsCnT/43c1RgTunpjla8486GirOApl/P8B0VXimwrquhkXxVItOYHX+O400UtC6C7MQ="
        # HAB_GITHUB_AUTH_TOKEN
        - secure: "bdKTLyo9UBM3dVf+qLn1+xpxo1s2ZHR34R5XNHWl/fpeWAnzlZrPDfGavqFxtcGmyWQ6oskEhw0CBZr80DktJm0EQ21QYNOaE80Kc0dSdbjUam+IiN9F2iG4AEueC5JZ9QC8PcBPCQvGF2rkfSCqfLwtDj0Uqj+lUyvmzVGHDtMohiYsXEo9l6aWfSnwRuF90PquyBdl2IwYjA8QVMH/2Z4chlpfPkvLKFN/E6aIP3B02uff9Y8Rox+toHZuFonjO3f2VfXk0BZk57TWAoB1cFYp7u+JkWlSKq70gTSs5mCmpTaS4vM02FyPiPRYW34sWxZhXBVwry4XCpOjGwZe+CKR2IC/M2GBWpLWoxqkoH9N1dI/vbNzh7yx8HQ7e+CSURRsJM7KcT7J6XYT/PFSQBbSDyrkXHbaJgwZzqAnKI14zP6uAKR7FFmA6IEfzuKuciE+Ms1T0Vi98RZyqlH4IXRRm6VSUGMKYUnghXWoT7lUFbC+iNFUrzrRHKHd1Bc7homl+K3yrFicaGSAE85lbU/KUjq8FAic8ASlhXr/ysve2M7t565mdd5W2jOXEdw4/qzHylu8ozo+XgSuH5HTrbd8gzffUpARZeaLc2TOd2rnS8ndhPNGwwm3dXWK9F7HvDGmVNHZ7XYm/1rWoo0dm3nlHMrmfMqGrOHI7bFe1T8="
      sudo: required
      addons:
        apt:
          packages:
          - ca-certificates
          - curl
          - wget
      cache:
        apt: true
        directories:
          - /root/travis_bootstrap
          - /hab/studios/home--travis--build--habitat-sh
          - /root/.cargo
      before_install:
        - ./support/ci/fast_pass.sh || exit 0
        - if [[ ! -x ./support/ci/deploy_unstable.sh ]]; then chmod +x ./support/ci/deploy_unstable.sh; fi
      script:
        - sudo ./support/ci/deploy_unstable.sh
notifications:
  webhooks:
    urls:
      - http://bots.habitat.sh:4567/travis
    on_success: always
    on_failure: always
    on_start: always
