branches:
  only:
    - master
    - /^sentinel.+$/
    - /^test_development-.*$/
env:
  global:
    - PATH=$HOME/.cargo/bin:$PATH
matrix:
  include:
    - os: linux
      language: ruby
      rvm: 2.3.1
      env:
        - AFFECTED_DIRS="components/hab|components/sup"
      sudo: required
      addons:
        apt:
          packages:
          - build-essential
          - ca-certificates
          - curl
          - wget
      cache:
        apt: true
        cargo: true
        directories:
          - /root/travis_bootstrap
      before_install:
        - ./support/ci/fast_pass.sh || exit 0
      script:
        - sudo ./support/ci/specs.sh
    - os: linux
      language: rust
      env:
        - COMPONENTS=bin LIBSODIUM_PREFIX=$HOME/pkgs/libsodium/1.0.8 LIBARCHIVE_PREFIX=$HOME/pkgs/libarchive/3.2.0 LIBZMQ_PREFIX=$HOME/pkgs/zeromq/4.1.4 PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$LIBARCHIVE_PREFIX/lib/pkgconfig:$LIBSODIUM_PREFIX/lib/pkgconfig:$LIBZMQ_PREFIX/lib/pkgconfig" LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LIBARCHIVE_PREFIX/lib:$LIBSODIUM_PREFIX/lib:$LIBZMQ_PREFIX/lib" LIBRARY_PATH="$LIBRARY_PATH:$LIBZMQ_PREFIX/lib"
        - AFFECTED_DIRS="components/director|components/hab|components/sup"
      rust: stable
      sudo: false
      addons:
        apt:
          sources:
            - kalakris-cmake
          packages:
            - build-essential
            - ca-certificates
            - cmake
            - curl
            - libbz2-dev
            - liblzma-dev
            - libprotobuf-dev
            - libssl-dev
            - pkg-config
      cache:
        apt: true
        cargo: true
        directories:
          - "$HOME/pkgs"
      before_install:
        - ./support/ci/fast_pass.sh || exit 0
        - ./support/ci/compile_libsodium.sh
        - ./support/ci/compile_libarchive.sh
        - ./support/ci/compile_zmq.sh
        - ./support/ci/install_rustfmt.sh
      script:
        - ./support/ci/rust_tests.sh
        - ./support/ci/lint.sh
    - os: linux
      language: rust
      env:
        - COMPONENTS=lib LIBSODIUM_PREFIX=$HOME/pkgs/libsodium/1.0.8 LIBARCHIVE_PREFIX=$HOME/pkgs/libarchive/3.2.0 LIBZMQ_PREFIX=$HOME/pkgs/zeromq/4.1.4 PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$LIBARCHIVE_PREFIX/lib/pkgconfig:$LIBSODIUM_PREFIX/lib/pkgconfig:$LIBZMQ_PREFIX/lib/pkgconfig" LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LIBARCHIVE_PREFIX/lib:$LIBSODIUM_PREFIX/lib:$LIBZMQ_PREFIX/lib" LIBRARY_PATH="$LIBRARY_PATH:$LIBZMQ_PREFIX/lib"
        - AFFECTED_DIRS="components/builder-dbcache|components/builder-protocol|components/common|components/core|components/builder-depot-client|components/http-client|components/net|components/butterfly"
      rust: stable
      sudo: false
      addons:
        apt:
          sources:
            - kalakris-cmake
          packages:
            - build-essential
            - ca-certificates
            - cmake
            - curl
            - libbz2-dev
            - liblzma-dev
            - libprotobuf-dev
            - libssl-dev
            - pkg-config
      cache:
        apt: true
        cargo: true
        directories:
          - "$HOME/pkgs"
      before_install:
        - ./support/ci/fast_pass.sh || exit 0
        - ./support/ci/compile_libsodium.sh
        - ./support/ci/compile_libarchive.sh
        - ./support/ci/compile_zmq.sh
        - ./support/ci/install_rustfmt.sh
      script:
        - ./support/ci/rust_tests.sh
        - ./support/ci/lint.sh
    - os: linux
      language: rust
      env:
        - COMPONENTS=srv LIBSODIUM_PREFIX=$HOME/pkgs/libsodium/1.0.8 LIBARCHIVE_PREFIX=$HOME/pkgs/libarchive/3.2.0 LIBZMQ_PREFIX=$HOME/pkgs/zeromq/4.1.4 PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$LIBARCHIVE_PREFIX/lib/pkgconfig:$LIBSODIUM_PREFIX/lib/pkgconfig:$LIBZMQ_PREFIX/lib/pkgconfig" LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LIBARCHIVE_PREFIX/lib:$LIBSODIUM_PREFIX/lib:$LIBZMQ_PREFIX/lib" LIBRARY_PATH="$LIBRARY_PATH:$LIBZMQ_PREFIX/lib"
        - AFFECTED_DIRS="components/builder-api|components/builder-admin|components/builder-jobsrv|components/builder-sessionsrv|components/builder-vault|components/builder-worker|components/builder-depot"
      rust: stable
      sudo: false
      addons:
        apt:
          sources:
            - kalakris-cmake
          packages:
            - build-essential
            - ca-certificates
            - cmake
            - curl
            - libbz2-dev
            - liblzma-dev
            - libprotobuf-dev
            - libssl-dev
            - pkg-config
      cache:
        apt: true
        cargo: true
        directories:
          - "$HOME/pkgs"
      before_install:
        - ./support/ci/fast_pass.sh || exit 0
        - ./support/ci/compile_libsodium.sh
        - ./support/ci/compile_libarchive.sh
        - ./support/ci/compile_zmq.sh
        - ./support/ci/install_rustfmt.sh
      script:
        - ./support/ci/rust_tests.sh
        - ./support/ci/lint.sh
    - os: linux
      language: node_js
      node_js: 4.4.3
      sudo: required
      env:
        - CXX=g++-4.8
        - AFFECTED_DIRS="components/builder-web"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - wget
      cache:
        apt: true
        directories:
          - components/builder-web/node_modules
          - components/builder-web/typings
      before_install:
        - ./support/ci/fast_pass.sh || exit 0
        - npm config set spin=false
      install:
        - "(cd components/builder-web && npm install)"
      script:
        - "(cd components/builder-web && npm run travis)"
        - sudo -E bash -c "./support/ci/build_builder_web.sh"
    - os: linux
      language: ruby
      rvm: 2.3.1
      sudo: false
      cache:
        bundle: true
        directories:
          - www/build
      env:
        - AFFECTED_DIRS="www"
        - AWS_BUCKET=habitat-www
        - AWS_DEFAULT_REGION=us-west-2
        - AWS_ACCESS_KEY_ID=AKIAJ2XVYOYEVJT77NJQ
        # AWS_SECRET_ACCESS_KEY
        - secure: "p9bQyftYcDPrmRpU3SUHj6xB/KH5jSiNqKoNMhXcQjasSV3nnPkGp18ZCKiRNO5WOMq8pX9mp6BENnHSj8WM9G8RxYK678fi+JIkTkrbtlcT8HAIRr4K3p0vD7y6G4xO3QuFbBY4FbD4WRdnrAQ1lgEQey5LHn5bGr95TDDVefN06ddDpE0wJE0/kBhC76ipZlmGuOwKmti1igvhmWHYWlYt7J4nFaTphpKi0NwrAtR2X5B+xnIhuy4I8dPBfYLA366acHMip/jvMf2v7JTSW5+WPIHDOTQy8cXvD4akokerGo+xMhClXoUNpBkdSW5arcyL8Zd4YWzsZHso4UXhMllU+fspPaZ6Lkz2Wor/oTWkqkMEAtX06Nxtb/47qjkoDAjHwoZrlrKqqVYE8/pYb6UAMJy/s92BD3dKKLitQ5ge62Sgc4wTl3p7aSDMbEDdzxBHfZPu+j2RmPkaTFeU4Zmuat1iSy5ca7Y+DvNk4Ryoh5Bt0oUs4MY4aviLY20g6VegfP/cbzdMhdUFjA36aVMOZ+4lK5sJoaYvyJFAAMJb2eLQQHcVkJ9v816K1R2EtuzggIBU6TRDZPsJfPMBd/LFBDaQzMX1BTO73Vd2Y8RK/DDDXDFMlW8xsC36UhvjKFEmixX3ZbC7I/CHuuok9eNnSB86xVMYU0iyXuC/wiY="
        # FASTLY_API_KEY
        - secure: "a376gD8mJCV6hzzugodQf+qXgVeivn4ElB8yHEAygMu94//62KT37TDlsfzCvcf1yth8jnWaJpQ+zDMCgNvo7IBiTRDingGXu+uEOheDjPssYuhwLUiTjKMb2cEdU78oEGKEWMTK6IYPJ8U6D/Q+odRevbnlS1zdUvNyNTcW3+41G83ZxFGsJCU2we5cw0w7NigqZaEG0yD6S7WPxOb+qxcZJ5/UQ/OKEnb68iIvvCJV782BcWZzxSUAyilPuRmZkfGgSQ9TZUMiKdf0KEtJfisxEBZX1s46sxAz4OssyIDM/0tp/bBnKJStyGYJODo5O6/dy2EkFd7YWsRhRoCkf+HXMQiG4V//CpNwkmTVUpNVpjoELkkLqqxew/bIN897H6pb4D4n7cUm5OFl5N6V798u67DWfSXxSsuwIc+INFkAYWEAakLJj0xt0K5WULPG84PWSPuNkBY/tqj/2wOiuFsdXQqFhzATvQa4fBEOyNBMS3knd2ovmAxpRDabeH05chE2+PvzSmP+avBIaRPuqBM2XdMqxVWrKfVsXQ+/Tezo3KqMujv5Zo4HR1Jlo4Yqnm75gDDYu1U0J3PMSERxpr8IP7bYb3511Th5KH3/pRQLaVXOCOGWXPMHk8ofN7u2rRDvWAbG4to56M1ZuHhVrGhpOuMT2uYpIjm83qWyFa0="
        # FASTLY_SERVICE_KEY
        - secure: "nIQy5W+YHwCed2DT0E0EG8wTOLeGIAGcQd4jO0holr+Ch/xGppk2Cnr2V41VK7AYr6y9aiABl9ku9nURQQzGlmYiG21jF6vrZpibEPj3/jPlyHfK5WwzNmsoJXJJiDfXCsC7uk4znbHSMZA1Tqg+bx3ExWpNJAv/LwRpwCjQ21UDD4Mh/yf7TRpcQy6XqKtJ2uJTT5mCNhBshafavYaWzdf2vqSn834DpqrDwXX+OgCoQno+erFxDbMzRHYR0/eQgKGcOsI9xn4zz7QfXE621rub9Q75c7P7XVgNatla5mVn/q7XCkReC/eAdRD7pYZyF5N+GOmm6kVRAzevmsXcKwkQJU6HdteKqYOvQKL+3LjY0YT/kri5FxkfC9jUKtBpYkaN1kotZ9tQp/ubwld/DDpTE73bCnEgyUCWmiI4FpLKg289R8/Li0BmysgsHHDUtrDFKUHo4YChUkIMKWeg5OpKVq8aXW3qiS6AhO24h7deYFtrB+jbl849QPcI+A9Ks46MRJJx6ws/s8Z7lfjiJW0rAomNkikCwBtWi4oLPXASpWr1s4aG+5gtYG3AqaLVVNj98TcvvcgivL6JLPctJDC4VVTcFn6fG7QSUL60jgHfFK333x5L7f2NVxJB/tRPgUSDO4XBD6O5M+j5RTXpwmqHo8kVCLSJrT6EyVHLmak="
      before_install: ./support/ci/fast_pass.sh || exit 0
      script: ./support/ci/deploy_website.sh
    - os: linux
      env:
        - AFFECTED_DIRS="Cargo\.toml|Cargo\.lock|components/hab|components/common|components/core|components/builder-depot-client|components/http-client|components/sup|components/butterfly"
        # HAB_ORIGIN_KEY
        - secure: "uZ70GE8qK3GBgs7ZIsoy5DhPlHNs2hoLxLBGKq+u+0XrE017pOnW6mNHsn7J7i2r8CPtd4KFsFEN52wZSA+Sf96MFIL2w9E+geykBgbRMZzv4icuCf0xSGwm4iRMgZ9A08TfurMX6y6N+4JNsrCv9syVNuGq09EL2wLHPXOQhesMpodijQLcFikxfEXXbaWla1xHnYxJk+fbvYDoXVCbdqnpdeLTmGuQHFaaNI7jm1B3L/dl+IGZxwFdvqBT3G9mHiXBdyi8bALs7rcZNdV7PqtFFpp98zIeqwNHtHPd5cBRmqDRTRxucRSACS/lurrz9J+001a9RjPvUkYlLrn0hQY9pN6oo+kCpN/1r0bc17i4FbGx7R73FnFgPK/cno0ENBFygNZn7/jg6cENgjkBlHsZhc1+L1xhILo46nQU9XbWJrwelVYUOOGXI76tECOkGhkglx1vYK8fcMVLJMhL7psgPpbGbDJQDuAKhHS+75txNK+356ompNL+YUzeWZc4KSGZCNTQsPK+rsGttmA+JXtAaquFaY5xwSgyKHwETiSVg4dYXb3xh6goNxf2JTOZOosWaypyykHqcqsqCu2fzIDdmkgCx6I5/5q8I/7Z0es0jlUpHamlihZwe4E5YdYFCSouaDoeTnVdJKVI1p9fnAjpFqjivFgqLE/Z504vCNU="
        - BINTRAY_USER=smurawski
        # BINTRAY_KEY
        - secure: "CHOiAfgFYbUBwYNIx7yJ7Y6697IzoX5zZtxHnByblU7Mei990vP+wUMjWrp2OY4I5UKdfSg5bkUtkEHBMUdoaiZZB+420dnZWPX94hQEYAGSdFzsgZlNZlu9vwnHout6+tDhylW0eIv7yMB1BViyOpeGxJ5rgCCmdDBEF5uWfnzuOMSeaOmcMQe24mzHY7vxIwfqJwEbVD08AOtJXVp2Kk0nLoA0GfJS1ZCcibK6TbXuZfUwYmF9jaZZdQj26UH8KtkiKYLy4Ti1c54XLwVahGeszBdi3xCAY6OWidAaTtnvEahtltXRl0HQCmhgLxpuZ/94lB4Mo4TqSf9NgZS7pqDB35YpYddy2hwW5HZFZlZoXgAqCTT+70NB0hoICpvNlvo4p7zRB7PVHbipgg64eA/OlLW+Bd4KXTHn+y+JrN1g9pDR9YF2lVewbmtzKbmxgQZYIrSK9SVZNP30DeN6uoedAxFFZGqgmPoC6Fcu5HG9Y1BY08HRVwRxLtLj8bciKgMHLNSKfVOdNlFac9nGn65aqenRGEmCd4wyjMZ7gd74V75aMdZozhFacDva0Qw5hRzhnJ8rYXBzG0juyodznMtVCARlRijPn0TW9LjYNb8+5f7LoxtywRmCNwYBB1OWghOePhWGMHBVAYTLzalIkX4WR0fc+xdhOq6lfAbgU4s="
        # BINTRAY_PASSPHRASE
        - secure: "XkZuLadu8aGACYdDN9QLUvuuGciiC8PahELGn2gfI8ILeIozzsWCclmNp2eKfduYsAu0otdps2dHAI1VwYH6+xGq+6byMMpXaXbQl3fahMe2vwaREpstmjbglWMNHcBqH4Bccx3aMxZjROO6NeT1U49uk7lKW+Enf+Dhw90L8sVP3v/xbmynYnue32heeQklkNH57RZ3uWJOUOPxOn5vcXsI0PqvJ8i53qIiUDQLivjLmOJUuudQiU/WP6rpewiIMoPO/REfyxq3gkCcYkzeXxytpVLEFwWjS6mvpLQbTJ+8/tp06sLXBxqknFboEWsqcraswROXi4ZXpubraFFNO/9jn9c1RaSmJqBEIQEK0/4K5VDYjukWMWpMQcwGq/I5dqUaDZJpoWPGqvw9b3zgsZNjlvLq2FEeuQEj2eD2Z4S5/PpgQRFhJMS+uMdPpingQMQAn9y83bZeDdtakWcX/IRjMBSF+UXCaXfTF9SWwURsCqakMEQhtZ+A3g5MAtZ6N/2QMsUcI7K56PjxXJiRSnZw821+VJgkpbk8Z8M2koZ6+Jy4jOGrUvDVGZ8umj3ipNmX8nFjP2s8jS7ihfIuG33p1fNw2397dEf0pDnPdsCnT/43c1RgTunpjla8486GirOApl/P8B0VXimwrquhkXxVItOYHX+O400UtC6C7MQ="
        # HAB_GITHUB_AUTH_TOKEN
        - secure: "bdKTLyo9UBM3dVf+qLn1+xpxo1s2ZHR34R5XNHWl/fpeWAnzlZrPDfGavqFxtcGmyWQ6oskEhw0CBZr80DktJm0EQ21QYNOaE80Kc0dSdbjUam+IiN9F2iG4AEueC5JZ9QC8PcBPCQvGF2rkfSCqfLwtDj0Uqj+lUyvmzVGHDtMohiYsXEo9l6aWfSnwRuF90PquyBdl2IwYjA8QVMH/2Z4chlpfPkvLKFN/E6aIP3B02uff9Y8Rox+toHZuFonjO3f2VfXk0BZk57TWAoB1cFYp7u+JkWlSKq70gTSs5mCmpTaS4vM02FyPiPRYW34sWxZhXBVwry4XCpOjGwZe+CKR2IC/M2GBWpLWoxqkoH9N1dI/vbNzh7yx8HQ7e+CSURRsJM7KcT7J6XYT/PFSQBbSDyrkXHbaJgwZzqAnKI14zP6uAKR7FFmA6IEfzuKuciE+Ms1T0Vi98RZyqlH4IXRRm6VSUGMKYUnghXWoT7lUFbC+iNFUrzrRHKHd1Bc7homl+K3yrFicaGSAE85lbU/KUjq8FAic8ASlhXr/ysve2M7t565mdd5W2jOXEdw4/qzHylu8ozo+XgSuH5HTrbd8gzffUpARZeaLc2TOd2rnS8ndhPNGwwm3dXWK9F7HvDGmVNHZ7XYm/1rWoo0dm3nlHMrmfMqGrOHI7bFe1T8="
      sudo: required
      addons:
        apt:
          packages:
          - ca-certificates
          - curl
          - wget
      cache:
        apt: true
        directories:
          - /root/travis_bootstrap
          - /hab/studios/home--travis--build--habitat-sh
          - /root/.cargo
      before_install:
        - ./support/ci/fast_pass.sh || exit 0
        - if [[ ! -x ./support/ci/deploy_unstable.sh ]]; then chmod +x ./support/ci/deploy_unstable.sh; fi
      script:
        - sudo ./support/ci/deploy_unstable.sh
    - os: osx
      osx_image: xcode6.4
      language: generic
      sudo: true
      before_install:
        - ./support/ci/fast_pass.sh || exit 0
      script: support/ci/macos-pkg.sh
      env:
        - AFFECTED_DIRS="Cargo\.toml|Cargo\.lock|components/hab|components/common|components/core|components/builder-depot-client|components/http-client"
        - secure: WUMBBYM1qMbmwXlf883rl6g5UqFTjtelawCOAhpSFSe9Kcit8HakutFr6b1NfTDF0b4S7R7YLj6j0Di2RP/Tk8brol/z/xmHHCWfFvadxhf/95HJbWmTeD0zDD3wpAbOfQCYHhSKYpLoXVpd/uZnnYLsTJNibFyO54SmOyApH0whHI0bYMZAOluB9vkIduH7Hv80lm4GA0xirHsuXYAirm0wYKdCx+ArWZfA9nci6NCa/D1swRvlmcnXeqvtTF3AJ5B6GP3+H5iDbam8anBe+dAe3YyqxTWw/+Th1h2F0h9Gghuh/dQNHZ7QqGV/rc5jY5jiRo41kptbgj8TBuY+4URsCfm/l5lKvm7GCtUp9LFq/rIaLLatp7mCwQeGwepWTnw9qe2scSP4XsyxusWbvxMQTfmccRq6dydwD1JgXy25pOKVTKY8uVk9THF5uvViYwsdUOGJWvkOHUZArHc0oSqi3cFp7DKTrP1nig4Oqd+9w6lbOPnEdWgGcu11k2rG/cpF0X/+sXD+CAR607ctVTxxW5WzZePtwqWqy5IujO4Uh8CnwUDB51TETbhIsteFHBwv2n08DUVEatew2sEhXJJ2eI3UMxnXPOFCI2197BoTjHU7FHW+z5Vx2JSKb6VTULCDHXYId4XjjVbh7WzyAEVkFituAcddqXpn6HOxqOo=
      deploy:
        on: master
        provider: bintray
        file: out/hab-bintray.json
        user:
          secure: "RAnTccM0w4ODqonvvAgTVwloxvr+9J7vIXhowlqupj7PXsCi6DhuAPn+ZkRI5XznO1y/j3l6YyCTzMqjn66Px+0xsl3lD4kI17I9iUuHUkyJQpVvZ4G+h0es4pzhmcpTJKLhyYDgYO8H0k+q2skuT0brmxjsr/oghiNks8eUT+brSp7XyqtFmxrqr+inILUFIRMIUcF93etshlBEYrOCSxlY9yrxZCjMkbo4fKEBHhckDXpVFmrHslQVVBkTUTTr0ef7Lbe2ynoWRplB/Sw27DPr+eLRGtD9LiHOh/XIDWBhkF1dwAIlydxLaBcJTzpu1V78HE61nGRVc86Qww/rmqh55OG4VvEXjeblop0mV3KBDNHVKgcG/UN9gcL3TiEMwWn0XB4aef9Lxt82LuyQ5jASpQE2ThPY6qIkVn7/RC+ADJA1PDFICm08t48x69anAsB1JEzP0I6xL2SqWQI/07pf9pqJJpfhdJTpbs8pNZnZiJujcxhNPrAxBPJyCy6wdGSyWmU8outDjfs58bR6bCmf4g+QyZA8VmWQxKJOjuaSHYCXQRW47wb+e2k1OAswK/FvGA/LWDDrDfdv3EwNVjI+usEDsEAbBsWG5Z3FIkszELZA9sY2Qyd6tpyxjSpwOfnZn55u8HjF1k2iPJqBGHWjLUQBQOjgyWVyl0p/1/g="
        key:
          secure: "M/sbm/YLwyE2kbB1o8dX46SohcvXJjo3Px9yINzPMz6Z2bHyYpz741D0hAomFGXfQbnIrMBD+HKK6w5NsP804rExzMD9p2gUVyOicDb7YbDs4AGoFqW7nAyk+/F2H2J3KGlZwHXSIIuStVyNYTi2OLbB0i7rX1u6Fl+hfRRtX8+tt4AtBcf91EtSZteeiOU+BjeuVX+4ZFnA0cuvqR4wOaWkybymRYLecCJBihOVrNJrJD/paGXdJ4K62MGS9O8CQIVtGJZAjH9U0q96+96gLhXJf8zl4vBrEV/nj+JbfAMVPZ0k8sQ1n8ANF2fUZsjad1LNaVJWRi87qknFcYUGx7DjsW/0RW5dQs6t1Sgo53Mf6RtIVIWF5pQYEmUuOz5X6VY3FT3P58lVQcd61+5gF6FTMnvJU7S45ERj4wvzzKYpyYC0bXmc2Djxi72/NdYhPPA0B/fJP0OSbpdIEAFrDOpWXuim2sWw+i7sUNZuwZ8RTOuMywyMtknVMYu9RuQUIpcGFsQmpih46evZWPcBCGagTwgPSmdcEtDP5pZ/cdeEThPgHItI0mwUvdwgISJ6UgayfMwHARW0tn5EatEdYp2cZYwaTIPORV6hpMyXC0eokZnE+Fz3bkE8k27t6lbDRq+mySOELxoMRrB9Kri7vRHWEJU9p2uaJnm0gmssCUc="
        passphrase:
          secure: "k1/k25G+jYIa3/B24vOg+6tdDk7CO9udp/G2HoPiyoNGFjpZoOWXKBQIdITI8rqbuRwUtc9GFKGQtdz2dXNzQs3A8+XfaAcebQL3AqBM2BG/MPm5EiIMt2XHVees+VoZfhhOZXKZIs78cPVC4QiVI+T5K/LrCsBowSTXp4AjOgK885sdd0oGD1SDfus7gei4vjeWkah/aKooNLsH9KPJ1OSvPgQccQysscHFwWCbdBK3vIe1w6Ay5oLPSQH/EbLtSGVuPlj5o4lReShFeC7dF/S3jv7Cwl1PrG2pBPTWuT/0J9o2TQkn0lsWaa2FF/lypJXpVEGFdxy1o9Tm28ZWVK+LXsmELg55CAGqOAc1YpwqxWgwqSzaO2SypeqK1z40tOeUJ8d9JAZaPZ0hZZPWxVqgAch+nXjLnPirJw/evBZb7UXBeiGHtO+v9W3twcCS2/NOubGUmJgfAdkBRKZKHYQQmps0TAe5aoQyC6l7cPx89rfz3t7/mNKbgE2+VcNPXn7gM3iznySEmjYTjTid4Erz9+Laiyr/skgwuyktpdIvVQjdw3TrbY+CtNUAWMr67qdbiDTBxV8BIeCiKX52kcp9EoITVK/85YZ98OgD2t7vpfWeqRZkztT3PlG0041OBSwItDLTHqFxaTWDkQ8dAYSk2V1CcHMhTEg0e3iCRiU="
notifications:
  webhooks:
    urls:
      - http://bots.habitat.sh:4567/travis
    on_success: always
    on_failure: always
    on_start: always
